#include <linux/mm_types.h>
/*
struct page
struct vma_struct
*/

#include <linux/mm.h>
/*
page_address()
page protection bit definitions e.g. VM_READ
remap_pfn_range()
*/

#include <linux/gfp.h>
/*
alloc_pages()
flags associated with alloc_pages
__free_pages
*/

#include "LAMbS_models.h"

struct  page    *LAMbS_models_pages = NULL;

u64 *instruction_retirement_rate;
u64 *energy_consumption_rate;
u64 *om_schedule;

int LAMbS_models_alloc_pages(void)
{
    int ret;
    
    int LAMbS_models_size = LAMbS_mo_count * 3 * sizeof(u64);
    
    if(LAMbS_MODELS_SIZE < LAMbS_models_size)
    {
        printk(KERN_INFO "LAMbS_models_alloc_pages: Given current limitations of the "
                        "kernel module, the number of modes of operation are too many!");
        ret = -EINVAL;
        goto error0;
    }
    
    //allocate pages (not in high memory)
    LAMbS_models_pages = alloc_pages(   (__GFP_WAIT | __GFP_REPEAT |  __GFP_ZERO), 
                                        LAMbS_MODELS_ORDER);
    if(NULL == LAMbS_models_pages)
    {
        printk(KERN_INFO "LAMbS_models_alloc_pages: alloc_pages failed for "
                        "LAMbS_models_pages");
        ret = -ENOMEM;
        goto error0;
    }

    if(NULL == page_address(LAMbS_models_pages))
    {
        //the allocated memory is in high memory, which is bad for us
        printk(KERN_INFO "LAMbS_models_alloc_pages: The LAMbS_models_pages are in high "
                        "memory!\n");
        ret = -ENOMEM;
        goto error1;
    }

    /*Setup the arrays*/
    instruction_retirement_rate = (u64*)page_address(LAMbS_models_pages);
    energy_consumption_rate = &(instruction_retirement_rate[LAMbS_mo_count]);
    om_schedule = &(energy_consumption_rate[LAMbS_mo_count]);

    return 0;
    
error1:
    __free_pages(LAMbS_models_pages, LAMbS_MODELS_ORDER);
    LAMbS_models_pages = NULL;
error0:
    return ret;
}

void LAMbS_models_init(void)
{
    int moi;
    
    for(moi = 0; moi < LAMbS_mo_count; moi++)
    {
        instruction_retirement_rate[moi] = 0;
        energy_consumption_rate[moi] = 0;
        om_schedule[moi] = 0;
    }
}

/*Do any processing necessary on the omschedule generated by the
allocator. This may involve sanitizing the schedule so that the
time spent in any OM is not less than the transition time*/
void LAMbS_models_process_omschedule(void)
{
    
}

void LAMbS_models_free_pages(void)
{
    /*Set all the array addresses to NULL*/
    instruction_retirement_rate = NULL;
    energy_consumption_rate = NULL;
    om_schedule = NULL;
    
    /*Free the page frames, set the page frame pointer to NULL*/
    __free_pages(LAMbS_models_pages, LAMbS_MODELS_ORDER);
    LAMbS_models_pages = NULL;
}

