
#define PBS_IOCTL_BWMGT_PERIOD 		0
#define PBS_IOCTL_BWMGT_ALLOC_RUNTIME	1
#define PBS_IOCTL_BWMGT_START			3
#define PBS_IOCTL_BWMGT_MAX			4

#define PBS_IOCTL_JBMGT_PERIOD 		0
#define PBS_IOCTL_JBMGT_SRT_RUNTIME		1
#define PBS_IOCTL_JBMGT_SRT_HISTLEN		3
#define PBS_IOCTL_JBMGT_START			4
#define PBS_IOCTL_JBMGT_MAX			5
