
%The purpose of this script is to generate a single tex file containing a table with the 
%timing data associated with each of the workloads. The table to be generated is as 
%follows:
%
%   Workload, Mean, Std, Max ACF, Max ACF Lag
%
%

    %Open the file
    report_name = '../timing_reports/fulltiming_summary_table.csv';
    fid = fopen(report_name, 'w');
    
    %Workload-related arrays
    datadir = '../timing_data_summary/';
    workload_list = {   
                        'ffmpeg/ffmpeg.enc.cc.wav.amr.mat', ...
                        'ffmpeg/ffmpeg.enc.arthur.wav.amr.mat', ...
                        'ffmpeg/ffmpeg.enc.vf18.wav.amr.mat', ...
                        'ffmpeg/ffmpeg.enc.cc.wav.opus.mat', ...
                        'ffmpeg/ffmpeg.enc.arthur.wav.opus.mat', ...
                        'ffmpeg/ffmpeg.enc.vf18.wav.opus.mat', ...
                        'ffmpeg/ffmpeg.enc.cc.wav.spx.mat', ...
                        'ffmpeg/ffmpeg.enc.arthur.wav.spx.mat', ...
                        'ffmpeg/ffmpeg.enc.vf18.wav.spx.mat', ...
                        ...
                        'ffmpeg/ffmpeg.dec.cc.amr.mat', ...
                        'ffmpeg/ffmpeg.dec.arthur.amr.mat', ...
                        'ffmpeg/ffmpeg.dec.vf18.amr.mat', ...
                        'ffmpeg/ffmpeg.dec.cc.opus.mat', ...
                        'ffmpeg/ffmpeg.dec.arthur.opus.mat', ...
                        'ffmpeg/ffmpeg.dec.vf18.opus.mat', ...
                        'ffmpeg/ffmpeg.dec.cc.spx.mat', ...
                        'ffmpeg/ffmpeg.dec.arthur.spx.mat', ...                        
                        'ffmpeg/ffmpeg.dec.vf18.spx.mat', ...
                        ...
                        'ffmpeg/ffmpeg.enc.arthur.wav.mp3.mat', ...
                        'ffmpeg/ffmpeg.enc.mozart.wav.mp3.mat', ...
                        'ffmpeg/ffmpeg.enc.sintel.wav.mp3.mat', ...
                        'ffmpeg/ffmpeg.enc.dsailors.wav.mp3.mat', ...
                        'ffmpeg/ffmpeg.enc.beethoven.wav.mp3.mat', ...
                        'ffmpeg/ffmpeg.enc.arthur.wav.ogg.mat', ...
                        'ffmpeg/ffmpeg.enc.mozart.wav.ogg.mat', ...
                        'ffmpeg/ffmpeg.enc.sintel.wav.ogg.mat', ...
                        'ffmpeg/ffmpeg.enc.dsailors.wav.ogg.mat', ...
                        'ffmpeg/ffmpeg.enc.beethoven.wav.ogg.mat', ...
                        ...
                        'ffmpeg/ffmpeg.dec.arthur.mp3.mat', ...
                        'ffmpeg/ffmpeg.dec.mozart.mp3.mat', ...
                        'ffmpeg/ffmpeg.dec.beethoven.mp3.mat', ...
                        'ffmpeg/ffmpeg.dec.sintel.mp3.mat', ...
                        'ffmpeg/ffmpeg.dec.dsailors.mp3.mat', ...
                        ...
                        'ffmpeg/ffmpeg.dec.audio.bigbuckbunnyfull.mov.mat', ...
                        'ffmpeg/ffmpeg.dec.audio.sintelfull.mkv.mat', ...
                        ...
                        'ffmpeg/ffmpeg.dec.arthur.vorbis.mat', ...
                        'ffmpeg/ffmpeg.dec.mozart.vorbis.mat', ...
                        'ffmpeg/ffmpeg.dec.beethoven.vorbis.mat', ...
                        'ffmpeg/ffmpeg.dec.sintel.vorbis.mat', ...
                        'ffmpeg/ffmpeg.dec.dsailors.vorbis.mat', ...
                        ...
                        'ffmpeg/ffmpeg.enc.bridge_close.y4m.webm.mat', ...
                        'ffmpeg/ffmpeg.enc.deadline.y4m.webm.mat', ...
                        'ffmpeg/ffmpeg.enc.highway.y4m.webm.mat', ...
                        'ffmpeg/ffmpeg.enc.mad900.y4m.webm.mat', ...
                        'ffmpeg/ffmpeg.enc.bridge_close.y4m.flv.mat', ...
                        'ffmpeg/ffmpeg.enc.deadline.y4m.flv.mat', ...
                        'ffmpeg/ffmpeg.enc.highway.y4m.flv.mat', ...
                        'ffmpeg/ffmpeg.enc.mad900.y4m.flv.mat', ...
                        'ffmpeg/ffmpeg.enc.bridge_close.y4m.mp4.mat', ...
                        'ffmpeg/ffmpeg.enc.deadline.y4m.mp4.mat', ...
                        'ffmpeg/ffmpeg.enc.highway.y4m.mp4.mat', ...
                        'ffmpeg/ffmpeg.enc.mad900.y4m.mp4.mat', ...
                        ...
                        'ffmpeg/ffmpeg.dec.deadline.webm.mat', ...
                        'ffmpeg/ffmpeg.dec.highway.webm.mat', ...
                        'ffmpeg/ffmpeg.dec.sintel.webm.mat', ...
                        'ffmpeg/ffmpeg.dec.factory.webm.mat', ...
                        'ffmpeg/ffmpeg.dec.deadline.flv.mat', ... 
                        'ffmpeg/ffmpeg.dec.highway.flv.mat', ...   
                        'ffmpeg/ffmpeg.dec.sintel.flv.mat', ...
                        'ffmpeg/ffmpeg.dec.factory.flv.mat', ...  
                        'ffmpeg/ffmpeg.dec.deadline.mp4.mat', ...                          
                        'ffmpeg/ffmpeg.dec.highway.mp4.mat', ...
                        'ffmpeg/ffmpeg.dec.sintel.mp4.mat', ...
                        'ffmpeg/ffmpeg.dec.factory.mp4.mat', ...  
                        'ffmpeg/ffmpeg.dec.sintelfull.mkv.mat', ...
                        'ffmpeg/ffmpeg.dec.bigbuckbunnyfull.mov.mat', ...
                        'sqrwav/sqrwav.example.mat'};

    %Loop through each workload
    for w_i = 1:length(workload_list)
    
        %Get the corresponding matfile
        matfile_path = sprintf('%s/%s', datadir, workload_list{w_i});
        load(matfile_path);
    
        fprintf(fid, '%s.%s , %.2e , %.2e , %.2e , %.2f , %i \n', ...
                    summary.application, ...
                    summary.config, ...
                    summary.mean, ...
                    summary.std, ...
                    summary.max, ...
                    summary.max_acor(1), ...
                    summary.max_acor_lag(1));
    end

    %close the file
    fclose(fid);
    
